language: go
sudo: false
go_import_path: github.com/pires/go-proxyproto
go:
  - 1.12.x
install:
  - go get golang.org/x/tools/cmd/cover
script:
  - go fmt
  - go vet
  - go test -v -covermode=count -coverprofile=coverage.out
